/**
 * LabelWriter `DriverAdapter` — wires labelwriter-core into the
 * shared harness shell.
 *
 * Multi-engine model (plan-09): Twin Turbo + 450 Twin (`left` /
 * `right` roles, in-band roll-select on a single USB endpoint) and
 * 450 Duo + Duo 96 / Duo 128 (`label` / `tape` roles, two USB
 * interfaces, two protocols — `lw-450` paper + `d1-tape` tape) all
 * declare more than one `PrintEngine`. The shell renders engine tabs
 * iff `multiEngine.isMultiEngine(device)` returns true AND the device
 * declares >1 engine. Single-engine LWs (3xx/4xx/5xx) skip the tab
 * strip entirely (plan-09 hard rule: 6-LW renders identically to
 * today).
 *
 * Per-engine encoder dispatch picks the right encoder pair by
 * `engine.protocol`:
 *
 *   - `lw-450` / `lw-550` → `harness-core/labelwriter`
 *   - `d1-tape`           → `harness-core/labelmanager`
 *
 * The Twin `ESC q <addr>` roll-select prefix is generated by the
 * dispatch helper from `engine.bind.address` (LW Twin Turbo: `0x31`
 * left, `0x32` right). Single-engine devices and Duo's interface-
 * routed engines get a no-op prefix.
 */
import type { DriverAdapter, MockSpec } from '@thermal-label/harness-shell';
import type { PrintEngine, PrinterStatus, Transport } from '@thermal-label/contracts';
import { dispatchEncoder } from '@thermal-label/harness-core/labelwriter';
import type {
  HardwareReport,
  IdentitySnapshot,
  EngineReport,
  TransportReport,
} from '@thermal-label/harness-core/shared';
import {
  build550GetSku,
  buildStatusRequest,
  DEVICES,
  MEDIA,
  parseSkuInfo,
  parseStatus,
  SKU_INFO_BYTE_COUNT,
  statusByteCount,
  type LabelWriterAnyMedia,
  type LabelWriterDevice,
  type LabelWriterMedia,
  type LabelWriterTapeMedia,
  type SkuInfo,
} from '@thermal-label/labelwriter-core';
import { WebUsbTransport } from '@thermal-label/transport/web';
import type { MediaGroupKey, MediaSwatch } from '@thermal-label/harness-components/types';
import { MockTransport, type MockTarget } from './transport/mock';
import { buildLabelwriterUsbFilters, findDeviceByVidPid } from './transport/webusb-filters';
import { HARNESS_VERSION, DRIVER_VERSION } from './version';

const DRIVER_KEY = 'labelwriter';
const TARGET_REPO = 'thermal-label/labelwriter';

const STATUS_TIMEOUT_MS = 2_000;
const STATUS_POLL_TIMEOUT_MS = 1_500;

// ─── Mock targets ────────────────────────────────────────────────

interface MockMeta {
  vid: number;
  pid: number;
  key: string;
  name: string;
}

const MOCK_DEVICE_FOR_TARGET: Record<MockTarget, MockMeta> = {
  lw330turbo: { vid: 0x0922, pid: 0x0008, key: 'LW_330_TURBO', name: 'LabelWriter 330 Turbo' },
  lw550: { vid: 0x0922, pid: 0x0028, key: 'LW_550', name: 'LabelWriter 550' },
  lw5xl: { vid: 0x0922, pid: 0x002a, key: 'LW_5XL', name: 'LabelWriter 5XL' },
  lw_450_duo: { vid: 0x0922, pid: 0x0023, key: 'LW_450_DUO', name: 'LabelWriter 450 Duo' },
};

function deviceForMockTarget(target: MockTarget): LabelWriterDevice {
  const meta = MOCK_DEVICE_FOR_TARGET[target];
  const device = findDeviceByVidPid(meta.vid, meta.pid);
  if (!device) {
    throw new Error(`Mock target ${target} has no matching DEVICES entry — fix mock.ts`);
  }
  return device;
}

function mockTargetSpec(target: MockTarget): MockSpec<LabelWriterDevice> {
  const meta = MOCK_DEVICE_FOR_TARGET[target];
  return {
    displayName: meta.name,
    device: deviceForMockTarget(target),
    vid: meta.vid,
    pid: meta.pid,
    aliases: aliasesFor(target),
  };
}

function aliasesFor(target: MockTarget): readonly string[] {
  switch (target) {
    case 'lw330turbo':
      return ['LW_330_TURBO'];
    case 'lw550':
      return ['LW_550'];
    case 'lw5xl':
      return ['LW_5XL'];
    case 'lw_450_duo':
      return ['duo', 'LW_450_DUO'];
  }
}

// ─── Connect orchestration ───────────────────────────────────────

interface ConnectOutput {
  transports: Record<string, Transport>;
  device: LabelWriterDevice;
  identity: IdentitySnapshot;
  skuInfo?: SkuInfo;
}

async function openEngineTransports(
  usbDevice: USBDevice,
  device: LabelWriterDevice,
): Promise<Record<string, Transport>> {
  const transports: Record<string, Transport> = {};
  for (const engine of device.engines) {
    const interfaceNumber = engine.bind?.usb?.bInterfaceNumber;
    try {
      const t = await WebUsbTransport.fromDevice(
        usbDevice,
        interfaceNumber !== undefined ? { interfaceNumber } : undefined,
      );
      transports[engine.role] = t;
    } catch (err) {
      const detail = err instanceof Error ? err.message : String(err);
      // eslint-disable-next-line no-console -- diagnostic for partial-claim failures (Duo on platforms that restrict multi-interface paired devices); the surviving transports remain usable per plan-09 §rails-not-walls.
      console.warn(
        `[harness] Could not claim interface ${String(interfaceNumber ?? 0)} for engine ` +
          `"${engine.role}" on ${device.key}: ${detail}. The other engines remain available.`,
      );
    }
  }
  return transports;
}

function pickPrimaryTransport(
  transports: Record<string, Transport>,
  device: LabelWriterDevice,
): Transport | undefined {
  for (const engine of device.engines) {
    if (engine.protocol === 'd1-tape') continue;
    const t = transports[engine.role];
    if (t) return t;
  }
  return Object.values(transports)[0];
}

async function runStatusProbe(
  transport: Transport,
  device: LabelWriterDevice,
  identity: IdentitySnapshot,
): Promise<void> {
  const wireOut = buildStatusRequest(device, 0);
  const wireIn = statusByteCount(device);
  try {
    await transport.write(wireOut);
    const response = await transport.read(wireIn, STATUS_TIMEOUT_MS);
    const status = parseStatus(device, response);
    identity.extra = {
      ...identity.extra,
      ready: status.ready,
      mediaLoaded: status.mediaLoaded,
      raw: Array.from(response.subarray(0, Math.min(response.length, 32))),
      ...(status.errors.length > 0 ? { errors: status.errors.map(e => e.code) } : {}),
    };
  } catch (err) {
    identity.extra = {
      ...identity.extra,
      statusProbeError: err instanceof Error ? err.message : String(err),
    };
  }
}

async function runSkuProbe(
  transport: Transport,
  device: LabelWriterDevice,
): Promise<SkuInfo | undefined> {
  const detects = device.engines[0]?.capabilities?.mediaDetection === true;
  if (!detects) return undefined;
  try {
    await transport.write(build550GetSku());
    const response = await transport.read(SKU_INFO_BYTE_COUNT, STATUS_TIMEOUT_MS);
    return parseSkuInfo(response);
  } catch {
    return undefined;
  }
}

async function connectReal(): Promise<ConnectOutput> {
  const filters = buildLabelwriterUsbFilters();
  const usbDevice = await navigator.usb.requestDevice({ filters: [...filters] });
  const vid = usbDevice.vendorId;
  const pid = usbDevice.productId;
  const device = findDeviceByVidPid(vid, pid);
  if (!device) {
    throw new Error(
      `No labelwriter device matched vid=0x${vid.toString(16)} pid=0x${pid.toString(16)}. ` +
        `The browser picker selected an unknown PID. Open the manual VID/PID drawer to override.`,
    );
  }

  const transports = await openEngineTransports(usbDevice, device);
  const primary = pickPrimaryTransport(transports, device);
  if (!primary) {
    throw new Error(
      `No engine transport could be opened for ${device.key}. Browser may have refused to ` +
        `claim the printer-class interface (some platforms restrict this for paired devices); ` +
        `unplug + replug the printer and retry, or use verify-cli.`,
    );
  }

  const identity: IdentitySnapshot = {
    advertisedName: usbDevice.productName ?? device.name,
    vid,
    pid,
  };
  await runStatusProbe(primary, device, identity);
  const skuInfo = await runSkuProbe(primary, device);
  if (skuInfo) {
    identity.extra = { ...identity.extra, detectedSku: skuInfo.sku };
  }

  return skuInfo ? { transports, device, identity, skuInfo } : { transports, device, identity };
}

async function connectMock(target: MockTarget): Promise<ConnectOutput> {
  const transport = MockTransport.open(target);
  const meta = MockTransport.identityFor(target);
  const device = findDeviceByVidPid(meta.vid, meta.pid);
  if (!device) {
    throw new Error(`Mock target ${target} has no matching DEVICES entry — fix mock.ts`);
  }
  const identity: IdentitySnapshot = {
    advertisedName: `${meta.name} (mock)`,
    vid: meta.vid,
    pid: meta.pid,
    extra: { mocked: true, mockTarget: target },
  };
  await runStatusProbe(transport, device, identity);
  const skuInfo = await runSkuProbe(transport, device);
  if (skuInfo) {
    identity.extra = { ...identity.extra, detectedSku: skuInfo.sku };
  }

  // Mock targets share the one transport across every declared engine
  // role so the multi-engine shape stays consistent
  // (`transports[role]` always resolves on Duo's mock target).
  const transports: Record<string, Transport> = {};
  for (const engine of device.engines) {
    transports[engine.role] = transport;
  }
  return skuInfo ? { transports, device, identity, skuInfo } : { transports, device, identity };
}

// ─── Media-picker bindings ───────────────────────────────────────

function isLabelMedia(m: unknown): m is LabelWriterMedia {
  if (typeof m !== 'object' || m === null) return false;
  const t = (m as { type?: string }).type;
  return t === 'die-cut' || t === 'continuous';
}

function isTapeMedia(m: unknown): m is LabelWriterTapeMedia {
  if (typeof m !== 'object' || m === null) return false;
  return (m as { type?: string }).type === 'tape';
}

function filterByDeviceEngine(
  media: readonly LabelWriterAnyMedia[],
  _device: LabelWriterDevice,
  engine: PrintEngine,
): readonly LabelWriterAnyMedia[] {
  const isTape = engine.protocol === 'd1-tape';
  const all = media as readonly unknown[];
  const byType = isTape ? all.filter(isTapeMedia) : all.filter(isLabelMedia);
  const compat = engine.mediaCompatibility;
  if (compat === undefined) return byType;
  return byType.filter(m => {
    const targets = m.targetModels ?? [];
    return targets.some(t => compat.includes(t));
  });
}

const PRIMARY_LABEL_CATEGORIES = new Set(['address', 'shipping', 'multi-purpose']);

function groupBy(m: LabelWriterAnyMedia): MediaGroupKey {
  if (isTapeMedia(m)) {
    const isRhino = typeof m.material === 'string' && m.material.startsWith('rhino-');
    if (isRhino) {
      return {
        key: `rhino-${String(m.tapeWidthMm)}mm`,
        label: `Rhino industrial — ${String(m.tapeWidthMm)} mm`,
        priority: 'secondary',
        sort: m.tapeWidthMm,
      };
    }
    return {
      key: `tape-${String(m.tapeWidthMm)}mm`,
      label: `${String(m.tapeWidthMm)} mm tape`,
      priority: 'primary',
      sort: m.tapeWidthMm,
    };
  }
  const cat = m.category ?? 'other';
  const isPrimary = PRIMARY_LABEL_CATEGORIES.has(cat);
  return {
    key: `cat-${cat}`,
    label: cat
      .split('-')
      .map(w => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' '),
    priority: isPrimary ? 'primary' : 'secondary',
  };
}

function swatch(m: LabelWriterAnyMedia): MediaSwatch | null {
  if (!isTapeMedia(m)) return null;
  const out: MediaSwatch = {};
  if (m.text !== undefined) out.fg = m.text;
  if (m.background !== undefined) out.bg = m.background;
  return out;
}

// ─── DriverAdapter ───────────────────────────────────────────────

export const adapter: DriverAdapter<LabelWriterDevice, LabelWriterAnyMedia, PrinterStatus> = {
  driverKey: DRIVER_KEY,
  driverDisplayName: 'LabelWriter',
  targetRepo: TARGET_REPO,
  harnessVersion: HARNESS_VERSION,
  driverVersion: DRIVER_VERSION,

  devices: Object.values(DEVICES),
  deviceKey: d => d.key,
  deviceName: d => d.name,
  findDeviceByVidPid,

  connect: async opts => {
    const result = opts.mock
      ? await connectMock((opts.mockTarget ?? 'lw330turbo') as MockTarget)
      : await connectReal();
    return {
      transports: result.transports,
      device: result.device,
      identity: result.identity,
      mocked: opts.mock,
    };
  },

  mockTargets: {
    lw330turbo: mockTargetSpec('lw330turbo'),
    lw550: mockTargetSpec('lw550'),
    lw5xl: mockTargetSpec('lw5xl'),
    lw_450_duo: mockTargetSpec('lw_450_duo'),
  },
  defaultMockTarget: 'lw330turbo',

  status: {
    kind: 'poll',
    intervalMs: 4000,
    read: async (transport, device) => {
      await transport.write(buildStatusRequest(device, 0));
      const response = await transport.read(statusByteCount(device), STATUS_POLL_TIMEOUT_MS);
      return parseStatus(device, response);
    },
    toPills: (status, ctx) => {
      const isTape = ctx.engine?.protocol === 'd1-tape';
      const noun = isTape ? 'tape' : 'paper';
      if (!status) {
        return {
          printer: { state: 'unknown', label: 'Printer: checking…' },
          media: { state: 'unknown', label: `${noun}: checking…` },
        };
      }
      const printer: { state: 'unknown' | 'good' | 'warn' | 'bad'; label: string } = !status.ready
        ? status.errors.some(e => e.code === 'no_media')
          ? { state: 'bad', label: 'No paper loaded' }
          : status.errors.some(e => e.code === 'paper_jam')
            ? { state: 'bad', label: 'Paper jam' }
            : { state: 'bad', label: 'Printer not ready' }
        : { state: 'good', label: 'Printer ready' };
      const jam = status.errors.some(e => e.code === 'paper_jam');
      const media: { state: 'unknown' | 'good' | 'warn' | 'bad'; label: string } =
        !status.mediaLoaded
          ? { state: 'bad', label: `No ${noun} loaded` }
          : jam
            ? { state: 'warn', label: `${noun} loaded — jam reported` }
            : {
                state: 'good',
                label: `${noun.charAt(0).toUpperCase()}${noun.slice(1)} loaded`,
              };
      return { printer, media };
    },
  },

  media: Object.values(MEDIA),
  mediaPicker: {
    filterByDeviceEngine,
    groupBy,
    swatch,
    describe: m => m.name,
    defaultMediaId: (_d, engine) =>
      engine.protocol === 'd1-tape' ? 'd1-standard-bw-12' : 'address-standard',
    detectionCapability: (_d, engine) => {
      if (engine.protocol === 'd1-tape') return 'none';
      return engine.capabilities?.mediaDetection === true ? 'auto-suggest' : 'none';
    },
    // LW 5xx's NFC SKU comes from a one-shot probe at connect time
    // (stashed on `identity.extra.detectedSku`), not from polled
    // status — so we ignore the new `status` arg here.
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    detected: (identity, available, engine, _status) => {
      if (engine.protocol === 'd1-tape') return null;
      const sku = identity.extra?.detectedSku;
      if (typeof sku !== 'string') return null;
      return (
        available.find(m => {
          const skus = (m as LabelWriterMedia).skus;
          return Array.isArray(skus) && skus.includes(sku);
        }) ?? null
      );
    },
    sectionTitle: engine =>
      engine.protocol === 'd1-tape' ? 'Pick the loaded D1 tape' : 'Pick the loaded label',
    warning: device => {
      if (device.transports.usb) return null;
      return (
        `${device.name} declares no USB transport — only TCP-9100 / Wi-Fi. ` +
        `Browsers cannot open raw TCP sockets, so this transport is CLI-only ` +
        `(install verify-cli) or use a USB-capable model.`
      );
    },
    customDimensions: {
      supports: (_d, engine) => engine.protocol !== 'd1-tape',
      build: ({ widthMm, lengthMm }) =>
        ({
          id: `custom-${String(widthMm)}x${String(lengthMm)}`,
          name: `Custom ${String(widthMm)}×${String(lengthMm)} mm`,
          category: 'die-cut',
          widthMm,
          heightMm: lengthMm,
          type: 'die-cut',
          targetModels: ['lw'],
        }) as unknown as LabelWriterAnyMedia,
      defaultWidthMm: 28,
      defaultLengthMm: 89,
    },
  },

  // Top-level encoder used when no per-engine override fires. The
  // multi-engine dispatch below replaces this for every engine, so
  // this branch only runs when a future single-engine driver-shaped
  // adapter consumer skips `multiEngine`. We still wire it for
  // type-soundness.
  encoder: {
    buildBitmap: ({ device, engine, media, harnessVersion, driverVersion }) =>
      dispatchEncoder({
        device,
        engine,
        media,
        harnessVersion,
        driverVersion,
      }).buildBitmap(),
    encodeBytes: (bitmap, device, media, engine, labelLengthDots) =>
      dispatchEncoder({
        device,
        engine,
        media,
        harnessVersion: HARNESS_VERSION,
        driverVersion: DRIVER_VERSION,
      }).encodeBitmap(bitmap, labelLengthDots),
    chunkSize: 64,
    chunkDelayMs: 5,
  },

  multiEngine: {
    isMultiEngine: device => device.engines.length > 1,
    // Per-engine encoder dispatch. The shell calls
    // `engineEncoder(engine)` once per print and uses the returned
    // pair for both `buildBitmap` and `encodeBytes`. Twin's `ESC q`
    // roll-select prefix is generated inside `dispatchEncoder` from
    // `engine.bind.address`.
    engineEncoder: () => adapter.encoder,
  },

  buildReport: ({
    device,
    identity,
    primarySession,
    allSessions,
    multiEngine,
    mocked,
    reporter,
  }) => {
    if (primarySession.rung === null || primarySession.media === null) {
      throw new Error('buildReport: primary session must have rung and media set.');
    }
    const usb = device.transports.usb;
    const transportReport: TransportReport = {
      name: 'usb',
      patterns: { diagnostic: 'pass' },
      rung: primarySession.rung,
      ...(primarySession.notes.trim() ? { notes: primarySession.notes.trim() } : {}),
    };
    const detected: IdentitySnapshot = {
      ...identity,
      extra: { ...identity.extra, ...(mocked ? { mocked: true } : {}) },
    };
    const engineReports: EngineReport[] = allSessions.flatMap<EngineReport>(s => {
      if (s.rung === null || s.media === null) return [];
      return [
        {
          role: s.engine.role,
          mediaKey: String(s.media.id),
          rung: s.rung,
          ...(s.notes.trim() ? { notes: s.notes.trim() } : {}),
        },
      ];
    });
    return {
      schemaVersion: 1,
      driver: DRIVER_KEY,
      driverVersion: DRIVER_VERSION,
      harnessVersion: HARNESS_VERSION,
      device: {
        detected,
        confirmed: {
          model: device.name,
          ...(usb ? { vid: parseInt(usb.vid, 16), pid: parseInt(usb.pid, 16) } : {}),
          overrides: { label: String(primarySession.media.id) },
        },
      },
      transports: [transportReport],
      ...(multiEngine && engineReports.length > 0 ? { engines: engineReports } : {}),
      submittedAt: new Date().toISOString(),
      ...(reporter ? { reporter: { handle: reporter } } : {}),
    } satisfies HardwareReport;
  },
};
